language: python
python:
- '2.7'

install:
- pip install -r requirements.txt
- pip install coveralls

notifications:
  email:
    on_failure: never

script: nosetests --with-coverage

after_success: coveralls