version: 2

jobs:
  build:
    working_directory: ~/One-Hot-Encoding-Example

  machine:
    post:
      - pyenv global 2.7.10

  dependencies:
    pre:
      - pip install numpy

  test:
    override:
      - pytest test-one-hot-encoding.py
